### PR TITLE
Creating about us page

### PR DESCRIPTION
**Pull request by sreyab**

### CODE REVIEW

**Comment by ck7286** [comment]
@sreyab please make your file text pink

**Comment by sreyab** [comment]
@ck7286 that sounds awesome.. :+1: 
changed font color

**Comment by zappabruno** [comment]
@sreyab  Hey, why don't you add a short bio?

**Comment by sreyab** [comment]
@zappabruno thats a great idea

**Comment by debbhad** [comment]
SB, can you please add a short description as well? The page isn't descriptive enough.

**Comment by sreyab** [comment]
@debbhad sure. thanks for the insight

**Comment by sreyab** [comment]
@debbhad hope you like the changes

**Pull request merged**
